version: '3'

services:

  frontend:
    image: engiball/taskapp:0.99
    ports:
      - 4444:80
    depends_on:
      - backend

  backend:
    image: engiball/taskapi:0.99
    environment:
      - DB_HOST=database
      - DB_USERNAME=task
      - DB_DATABASE=task
      - DB_PASSWORD=secret
    ports:
      - 5555:80
    depends_on:
      - database
    command: ./test.sh

  database:
    image: mysql:5.7
    environment:
      - MYSQL_DATABASE=task
      - MYSQL_USER=task
      - MYSQL_PASSWORD=secret
      - MYSQL_ROOT_PASSWORD=secret
    ports:
      - 33061:3306



